//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesStoreFE.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Stores", Namespace="http://schemas.datacontract.org/2004/07/WcfShoesStore")]
    [System.SerializableAttribute()]
    public partial class tbl_Stores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string storeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string storeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string storeAddress {
            get {
                return this.storeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.storeAddressField, value) != true)) {
                    this.storeAddressField = value;
                    this.RaisePropertyChanged("storeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string storeName {
            get {
                return this.storeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.storeNameField, value) != true)) {
                    this.storeNameField = value;
                    this.RaisePropertyChanged("storeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Articles", Namespace="http://schemas.datacontract.org/2004/07/WcfShoesStore")]
    [System.SerializableAttribute()]
    public partial class tbl_Articles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int articleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articlePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleTotalInShelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleTotalInVaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleDescription {
            get {
                return this.articleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.articleDescriptionField, value) != true)) {
                    this.articleDescriptionField = value;
                    this.RaisePropertyChanged("articleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int articleId {
            get {
                return this.articleIdField;
            }
            set {
                if ((this.articleIdField.Equals(value) != true)) {
                    this.articleIdField = value;
                    this.RaisePropertyChanged("articleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleName {
            get {
                return this.articleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.articleNameField, value) != true)) {
                    this.articleNameField = value;
                    this.RaisePropertyChanged("articleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articlePrice {
            get {
                return this.articlePriceField;
            }
            set {
                if ((object.ReferenceEquals(this.articlePriceField, value) != true)) {
                    this.articlePriceField = value;
                    this.RaisePropertyChanged("articlePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleTotalInShelf {
            get {
                return this.articleTotalInShelfField;
            }
            set {
                if ((object.ReferenceEquals(this.articleTotalInShelfField, value) != true)) {
                    this.articleTotalInShelfField = value;
                    this.RaisePropertyChanged("articleTotalInShelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleTotalInVault {
            get {
                return this.articleTotalInVaultField;
            }
            set {
                if ((object.ReferenceEquals(this.articleTotalInVaultField, value) != true)) {
                    this.articleTotalInVaultField = value;
                    this.RaisePropertyChanged("articleTotalInVault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/WcfShoesStore")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int articleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articlePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleTotalInShelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string articleTotalInVaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string storeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleDescription {
            get {
                return this.articleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.articleDescriptionField, value) != true)) {
                    this.articleDescriptionField = value;
                    this.RaisePropertyChanged("articleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int articleId {
            get {
                return this.articleIdField;
            }
            set {
                if ((this.articleIdField.Equals(value) != true)) {
                    this.articleIdField = value;
                    this.RaisePropertyChanged("articleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleName {
            get {
                return this.articleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.articleNameField, value) != true)) {
                    this.articleNameField = value;
                    this.RaisePropertyChanged("articleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articlePrice {
            get {
                return this.articlePriceField;
            }
            set {
                if ((object.ReferenceEquals(this.articlePriceField, value) != true)) {
                    this.articlePriceField = value;
                    this.RaisePropertyChanged("articlePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleTotalInShelf {
            get {
                return this.articleTotalInShelfField;
            }
            set {
                if ((object.ReferenceEquals(this.articleTotalInShelfField, value) != true)) {
                    this.articleTotalInShelfField = value;
                    this.RaisePropertyChanged("articleTotalInShelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string articleTotalInVault {
            get {
                return this.articleTotalInVaultField;
            }
            set {
                if ((object.ReferenceEquals(this.articleTotalInVaultField, value) != true)) {
                    this.articleTotalInVaultField = value;
                    this.RaisePropertyChanged("articleTotalInVault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string storeName {
            get {
                return this.storeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.storeNameField, value) != true)) {
                    this.storeNameField = value;
                    this.RaisePropertyChanged("storeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStores", ReplyAction="http://tempuri.org/IService1/GetStoresResponse")]
        ShoesStoreFE.ServiceReference1.tbl_Stores[] GetStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStores", ReplyAction="http://tempuri.org/IService1/GetStoresResponse")]
        System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.tbl_Stores[]> GetStoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStore", ReplyAction="http://tempuri.org/IService1/AddStoreResponse")]
        void AddStore(ShoesStoreFE.ServiceReference1.tbl_Stores sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStore", ReplyAction="http://tempuri.org/IService1/AddStoreResponse")]
        System.Threading.Tasks.Task AddStoreAsync(ShoesStoreFE.ServiceReference1.tbl_Stores sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyStore", ReplyAction="http://tempuri.org/IService1/ModifyStoreResponse")]
        void ModifyStore(ShoesStoreFE.ServiceReference1.tbl_Stores sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyStore", ReplyAction="http://tempuri.org/IService1/ModifyStoreResponse")]
        System.Threading.Tasks.Task ModifyStoreAsync(ShoesStoreFE.ServiceReference1.tbl_Stores sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveStore", ReplyAction="http://tempuri.org/IService1/RemoveStoreResponse")]
        void RemoveStore(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveStore", ReplyAction="http://tempuri.org/IService1/RemoveStoreResponse")]
        System.Threading.Tasks.Task RemoveStoreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticles", ReplyAction="http://tempuri.org/IService1/GetArticlesResponse")]
        ShoesStoreFE.ServiceReference1.tbl_Articles[] GetArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticles", ReplyAction="http://tempuri.org/IService1/GetArticlesResponse")]
        System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.tbl_Articles[]> GetArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticle", ReplyAction="http://tempuri.org/IService1/GetArticleResponse")]
        ShoesStoreFE.ServiceReference1.Article GetArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticle", ReplyAction="http://tempuri.org/IService1/GetArticleResponse")]
        System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.Article> GetArticleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticle", ReplyAction="http://tempuri.org/IService1/AddArticleResponse")]
        void AddArticle(ShoesStoreFE.ServiceReference1.tbl_Articles sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticle", ReplyAction="http://tempuri.org/IService1/AddArticleResponse")]
        System.Threading.Tasks.Task AddArticleAsync(ShoesStoreFE.ServiceReference1.tbl_Articles sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyArticle", ReplyAction="http://tempuri.org/IService1/ModifyArticleResponse")]
        void ModifyArticle(ShoesStoreFE.ServiceReference1.tbl_Articles sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifyArticle", ReplyAction="http://tempuri.org/IService1/ModifyArticleResponse")]
        System.Threading.Tasks.Task ModifyArticleAsync(ShoesStoreFE.ServiceReference1.tbl_Articles sobj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveArticle", ReplyAction="http://tempuri.org/IService1/RemoveArticleResponse")]
        void RemoveArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveArticle", ReplyAction="http://tempuri.org/IService1/RemoveArticleResponse")]
        System.Threading.Tasks.Task RemoveArticleAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ShoesStoreFE.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ShoesStoreFE.ServiceReference1.IService1>, ShoesStoreFE.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShoesStoreFE.ServiceReference1.tbl_Stores[] GetStores() {
            return base.Channel.GetStores();
        }
        
        public System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.tbl_Stores[]> GetStoresAsync() {
            return base.Channel.GetStoresAsync();
        }
        
        public void AddStore(ShoesStoreFE.ServiceReference1.tbl_Stores sobj) {
            base.Channel.AddStore(sobj);
        }
        
        public System.Threading.Tasks.Task AddStoreAsync(ShoesStoreFE.ServiceReference1.tbl_Stores sobj) {
            return base.Channel.AddStoreAsync(sobj);
        }
        
        public void ModifyStore(ShoesStoreFE.ServiceReference1.tbl_Stores sobj) {
            base.Channel.ModifyStore(sobj);
        }
        
        public System.Threading.Tasks.Task ModifyStoreAsync(ShoesStoreFE.ServiceReference1.tbl_Stores sobj) {
            return base.Channel.ModifyStoreAsync(sobj);
        }
        
        public void RemoveStore(int id) {
            base.Channel.RemoveStore(id);
        }
        
        public System.Threading.Tasks.Task RemoveStoreAsync(int id) {
            return base.Channel.RemoveStoreAsync(id);
        }
        
        public ShoesStoreFE.ServiceReference1.tbl_Articles[] GetArticles() {
            return base.Channel.GetArticles();
        }
        
        public System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.tbl_Articles[]> GetArticlesAsync() {
            return base.Channel.GetArticlesAsync();
        }
        
        public ShoesStoreFE.ServiceReference1.Article GetArticle(int id) {
            return base.Channel.GetArticle(id);
        }
        
        public System.Threading.Tasks.Task<ShoesStoreFE.ServiceReference1.Article> GetArticleAsync(int id) {
            return base.Channel.GetArticleAsync(id);
        }
        
        public void AddArticle(ShoesStoreFE.ServiceReference1.tbl_Articles sobj) {
            base.Channel.AddArticle(sobj);
        }
        
        public System.Threading.Tasks.Task AddArticleAsync(ShoesStoreFE.ServiceReference1.tbl_Articles sobj) {
            return base.Channel.AddArticleAsync(sobj);
        }
        
        public void ModifyArticle(ShoesStoreFE.ServiceReference1.tbl_Articles sobj) {
            base.Channel.ModifyArticle(sobj);
        }
        
        public System.Threading.Tasks.Task ModifyArticleAsync(ShoesStoreFE.ServiceReference1.tbl_Articles sobj) {
            return base.Channel.ModifyArticleAsync(sobj);
        }
        
        public void RemoveArticle(int id) {
            base.Channel.RemoveArticle(id);
        }
        
        public System.Threading.Tasks.Task RemoveArticleAsync(int id) {
            return base.Channel.RemoveArticleAsync(id);
        }
    }
}
